#############################################################################
# Makefile for building: tuxtorial
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sun Nov 14 19:32:27 2010
# Project:  tuxtorial.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile tuxtorial.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-lib \
		sub-client

lib//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	cd lib/ && $(QMAKE) /home/ideamonk/code/tuxtorial-client/lib/lib.pro -unix -o $(MAKEFILE)
sub-lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	cd lib/ && $(QMAKE) /home/ideamonk/code/tuxtorial-client/lib/lib.pro -unix -o $(MAKEFILE)
sub-lib: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE)
sub-lib-make_default: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) 
sub-lib-make_first: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) first
sub-lib-all: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) all
sub-lib-clean: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-lib-distclean: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lib-install_subtargets: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) install
sub-lib-uninstall_subtargets: lib//$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) uninstall
client//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) client/ || $(MKDIR) client/ 
	cd client/ && $(QMAKE) /home/ideamonk/code/tuxtorial-client/client/client.pro -unix -o $(MAKEFILE)
sub-client-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) client/ || $(MKDIR) client/ 
	cd client/ && $(QMAKE) /home/ideamonk/code/tuxtorial-client/client/client.pro -unix -o $(MAKEFILE)
sub-client: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE)
sub-client-make_default: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) 
sub-client-make_first: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) first
sub-client-all: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) all
sub-client-clean: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) clean
sub-client-distclean: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) distclean
sub-client-install_subtargets: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) install
sub-client-uninstall_subtargets: client//$(MAKEFILE) FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: tuxtorial.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile tuxtorial.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile tuxtorial.pro

qmake_all: sub-lib-qmake_all sub-client-qmake_all FORCE

make_default: sub-lib-make_default sub-client-make_default FORCE
make_first: sub-lib-make_first sub-client-make_first FORCE
all: sub-lib-all sub-client-all FORCE
clean: sub-lib-clean sub-client-clean FORCE
distclean: sub-lib-distclean sub-client-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-lib-install_subtargets sub-client-install_subtargets FORCE
uninstall_subtargets: sub-lib-uninstall_subtargets sub-client-uninstall_subtargets FORCE

sub-lib-check: lib/$(MAKEFILE)
	cd lib/ && $(MAKE) check
sub-client-check: client/$(MAKEFILE)
	cd client/ && $(MAKE) check
check: sub-lib-check sub-client-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

